<a href="https://colab.research.google.com/github/vssood/WU_DL/blob/master/WU_DL_WK2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import os
import numpy as np


## Introduction to Pandas

In [ ]:
csv_file = "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv"

In [ ]:
df = pd.read_csv(csv_file, na_values=['NA', '?'])

In [ ]:
df.head()

mpg  cylinders  displacement  ...  year  origin                       name
0  18.0          8         307.0  ...    70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...    70       1          buick skylark 320
2  18.0          8         318.0  ...    70       1         plymouth satellite
3  16.0          8         304.0  ...    70       1              amc rebel sst
4  17.0          8         302.0  ...    70       1                ford torino

[5 rows x 9 columns]

The display function provides a cleaner display than merely printing the data frame. Specifying the maximum rows and columns allows you to achieve greater control over the display.

In [ ]:
pd.set_option('display.max_columns', 7)
pd.set_option('display.max_rows', 5)
display(df)

mpg  cylinders  displacement  ...  year  origin  \
0    18.0          8         307.0  ...    70       1   
1    15.0          8         350.0  ...    70       1   
..    ...        ...           ...  ...   ...     ...   
396  28.0          4         120.0  ...    82       1   
397  31.0          4         119.0  ...    82       1   

                          name  
0    chevrolet chevelle malibu  
1            buick skylark 320  
..                         ...  
396                ford ranger  
397                 chevy s-10  

[398 rows x 9 columns]


It is possible to generate a second data frame to display statistical information about the first data frame.

In [ ]:
df1 = df.select_dtypes(include=['int', 'float'])
headers = list(df1.columns.values)

fields = []

for field in headers:
    fields.append({
        'name' : field,
        'mean' : df1[field].mean(),
        'Var'  : df1[field].var(),
        'std. Dev': df1[field].std()
    })

In [ ]:
for field in fields :
    print(field)

{'name': 'mpg', 'mean': 23.514572864321615, 'Var': 61.089610774274405, 'std. Dev': 7.815984312565782}
{'name': 'cylinders', 'mean': 5.454773869346734, 'Var': 2.8934154399199943, 'std. Dev': 1.7010042445332094}
{'name': 'displacement', 'mean': 193.42587939698493, 'Var': 10872.199152247364, 'std. Dev': 104.26983817119581}
{'name': 'horsepower', 'mean': 104.46938775510205, 'Var': 1481.5693929745862, 'std. Dev': 38.49115993282855}
{'name': 'weight', 'mean': 2970.424623115578, 'Var': 717140.9905256768, 'std. Dev': 846.8417741973271}
{'name': 'acceleration', 'mean': 15.568090452261291, 'Var': 7.604848233611381, 'std. Dev': 2.7576889298126757}
{'name': 'year', 'mean': 76.01005025125629, 'Var': 13.672442818627143, 'std. Dev': 3.697626646732623}
{'name': 'origin', 'mean': 1.5728643216080402, 'Var': 0.6432920268850575, 'std. Dev': 0.8020548777266163}


In [ ]:
pd.set_option( 'display.max_columns',  0)
pd.set_option('display.max_rows', 0)
df2 = pd.DataFrame(fields)
display(df2)

name         mean            Var    std. Dev
0           mpg    23.514573      61.089611    7.815984
1     cylinders     5.454774       2.893415    1.701004
2  displacement   193.425879   10872.199152  104.269838
3    horsepower   104.469388    1481.569393   38.491160
4        weight  2970.424623  717140.990526  846.841774
5  acceleration    15.568090       7.604848    2.757689
6          year    76.010050      13.672443    3.697627
7        origin     1.572864       0.643292    0.802055

### Missing Values

In [ ]:
df.shape

(398, 9)

In [ ]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

In [ ]:
df_ = df.loc[:, df.columns != 'name']


In [ ]:
df_[df_.applymap(np.isreal).all(1)]

mpg  cylinders  displacement  ...  acceleration  year  origin
0    18.0          8         307.0  ...          12.0    70       1
1    15.0          8         350.0  ...          11.5    70       1
2    18.0          8         318.0  ...          11.0    70       1
3    16.0          8         304.0  ...          12.0    70       1
4    17.0          8         302.0  ...          10.5    70       1
5    15.0          8         429.0  ...          10.0    70       1
6    14.0          8         454.0  ...           9.0    70       1
7    14.0          8         440.0  ...           8.5    70       1
8    14.0          8         455.0  ...          10.0    70       1
..    ...        ...           ...  ...           ...   ...     ...
389  22.0          6         232.0  ...          14.7    82       1
390  32.0          4         144.0  ...          13.9    82       3
391  36.0          4         135.0  ...          13.0    82       1
392  27.0          4         151.0  ...          17.3    82       1
393  27.0          4         140.0  ...          15.6    82       1
394  44.0          4          97.0  ...          24.6    82       2
395  32.0          4         135.0  ...          11.6    82       1
396  28.0          4         120.0  ...          18.6    82       1
397  31.0          4         119.0  ...          19.4    82       1

[398 rows x 8 columns]

In [ ]:
df_.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
year            0
origin          0
dtype: int64

In [ ]:
df_[df_.horsepower.isna() == True]

mpg  cylinders  displacement  ...  acceleration  year  origin
32   25.0          4          98.0  ...          19.0    71       1
126  21.0          6         200.0  ...          17.0    74       1
330  40.9          4          85.0  ...          17.3    80       2
336  23.6          4         140.0  ...          14.3    80       1
354  34.5          4         100.0  ...          15.8    81       2
374  23.0          4         151.0  ...          20.5    82       1

[6 rows x 8 columns]

Populate median value to the missing 

In [ ]:
med = df_.horsepower.median()
df_.horsepower.fillna(med, inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6245: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


In [ ]:
df_[df_.horsepower.isna() == True]

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, year, origin]
Index: []

### Outliers 

Those outside 3 sd 

In [ ]:
from sklearn import metrics
from scipy.stats import zscore

In [ ]:
df_.describe()

mpg   cylinders  ...        year      origin
count  398.000000  398.000000  ...  398.000000  398.000000
mean    23.514573    5.454774  ...   76.010050    1.572864
std      7.815984    1.701004  ...    3.697627    0.802055
min      9.000000    3.000000  ...   70.000000    1.000000
25%     17.500000    4.000000  ...   73.000000    1.000000
50%     23.000000    4.000000  ...   76.000000    1.000000
75%     29.000000    8.000000  ...   79.000000    2.000000
max     46.600000    8.000000  ...   82.000000    3.000000

[8 rows x 8 columns]

In [ ]:
# Show outliers in data
z = np.abs(zscore(df_))


In [ ]:
print(np.where(z>3))

(array([  6,   8,  13,  95, 116, 299, 394]), array([3, 3, 3, 3, 3, 5, 5]))


In [ ]:
# Data frame with high Z score values 
df_[np.abs(zscore(df_)) > 3]

mpg  cylinders  displacement  ...  acceleration  year  origin
6    14.0          8         454.0  ...           9.0    70       1
8    14.0          8         455.0  ...          10.0    70       1
13   14.0          8         455.0  ...          10.0    70       1
95   12.0          8         455.0  ...          11.0    73       1
116  16.0          8         400.0  ...           9.5    73       1
299  27.2          4         141.0  ...          24.8    79       2
394  44.0          4          97.0  ...          24.6    82       2

[7 rows x 8 columns]

In [ ]:
# Exclude data that has high z score value > 3 
df_ = df_[np.abs(zscore(df_)) <= 3]

In [ ]:
df_.shape

(3177, 8)

### Train & Test data split

In [ ]:
# Shuffle the data to split between train and test data 
df = df.reindex(np.random.permutation(df.index))

In [ ]:
mask = np.random.rand(len(df)) < .8

In [ ]:
mask[0: 25]

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True])

In [ ]:
train_df = pd.DataFrame(df[mask])
test_df = df[~mask]

In [ ]:
print(f'Train Dataset {len(train_df)}')
print(f'Test dataset {len(test_df)}')

Train Dataset 334
Test dataset 64


### Converting Data Frame to Matrix

Neural networks do not directly operate on Python data frames. A neural network requires a numeric matrix. The program uses the values property of a data frame to convert the data to a matrix.

In [ ]:
df[['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values

array([[ 13. ,   8. , 360. , ...,  11. ,  73. ,   1. ],
       [ 25. ,   4. ,  97.5, ...,  17. ,  72. ,   1. ],
       [ 22. ,   6. , 225. , ...,  15.4,  76. ,   1. ],
       ...,
       [ 14. ,   8. , 304. , ...,  11.5,  73. ,   1. ],
       [ 27.2,   4. , 119. , ...,  14.7,  78. ,   3. ],
       [ 24. ,   4. , 107. , ...,  14.5,  70. ,   2. ]])

### Save the dataset

In [ ]:
file_name_write = os.path.join('/content/', 'auto-mpg-shuffle.csv')

df.to_csv(file_name_write, index=False)

## Categorical and Continuous Values

In [ ]:
df.columns.values

array(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'], dtype=object)

In [ ]:
# Add Z score value for MPG 
df['mpg_zscore'] = zscore(df['mpg'])

In [ ]:
display(df)

mpg  cylinders  ...                        name  mpg_zscore
96   13.0          8  ...     amc ambassador brougham   -1.346959
58   25.0          4  ...          dodge colt hardtop    0.190289
191  22.0          6  ...            plymouth valiant   -0.194023
123  20.0          6  ...              toyota mark ii   -0.450231
341  23.5          6  ...          chevrolet citation   -0.001867
280  21.5          6  ...           pontiac lemans v6   -0.258075
271  23.2          4  ...            plymouth sapporo   -0.040298
337  32.4          4  ...                honda accord    1.138259
61   21.0          4  ...         ford pinto runabout   -0.322127
..    ...        ...  ...                         ...         ...
222  17.0          8  ...  oldsmobile cutlass supreme   -0.834543
198  33.0          4  ...                 honda civic    1.215121
368  27.0          4  ...    chevrolet cavalier wagon    0.446497
206  26.5          4  ...                  ford pinto    0.382445
145  32.0          4  ...                  datsun 710    1.087017
46   22.0          4  ...         chevrolet vega (sw)   -0.194023
86   14.0          8  ...                 amc matador   -1.218855
268  27.2          4  ...                  datsun 510    0.472118
21   24.0          4  ...                 audi 100 ls    0.062185

[398 rows x 10 columns]

### One-hot-encoding / dummy variables

In [ ]:
file_path = "https://data.heatonresearch.com/data/t81-558/jh-simple-dataset.csv"

In [ ]:
df_job = pd.read_csv(file_path, na_values=['NA', '?'])

In [ ]:
df_job.head()

id job area   income  ...  pop_dense  retail_dense     crime  product
0   1  vv    c  50876.0  ...   0.885827      0.492126  0.071100        b
1   2  kd    c  60369.0  ...   0.874016      0.342520  0.400809        c
2   3  pe    c  55126.0  ...   0.944882      0.724409  0.207723        b
3   4  11    c  51690.0  ...   0.889764      0.444882  0.361216        b
4   5  kl    d  28347.0  ...   0.744094      0.661417  0.068033        a

[5 rows x 14 columns]

Unique count of values

In [ ]:
for i in df_job.columns.values:
    print(i, df_job[i].nunique())

id 2000
job 33
area 4
income 897
aspect 356
subscriptions 6
dist_healthy 242
save_rate 273
dist_unhealthy 1407
age 24
pop_dense 106
retail_dense 203
crime 1301
product 7


One-hot-encoding of area into 4 different columns where 
The value A becomes [1,0,0,0] and the value B becomes [0,1,0,0].

In [ ]:
dummies = pd.get_dummies(['a','b','c','d'], prefix='area')
print(dummies)

   area_a  area_b  area_c  area_d
0       1       0       0       0
1       0       1       0       0
2       0       0       1       0
3       0       0       0       1


In [ ]:
# Using the above logic, generate dummies dataset from df_job
dummies = pd.get_dummies(df_job.area, prefix='area')

In [ ]:
df_job = pd.concat([df_job, dummies], axis=1 )

In [ ]:
df_job[['id','job','area','income','area_a',
                  'area_b','area_c','area_d']].head(5)

id job area   income  area_a  area_b  area_c  area_d
0   1  vv    c  50876.0       0       0       1       0
1   2  kd    c  60369.0       0       0       1       0
2   3  pe    c  55126.0       0       0       1       0
3   4  11    c  51690.0       0       0       1       0
4   5  kl    d  28347.0       0       0       0       1

As the categorical has been converted to numeric - drop the area 

In [ ]:
df_job.drop('area', axis = 1, inplace= True)

## 2.3 Grouping, sorting and shuffling

### Shuffling

In [ ]:
# Uncomment the line below to get the same shuffle each time
np. random.seed(42)
df = df.reindex(np.random.permutation(df.index))

display(df)

The following code demonstrates a reindex. Notice how the reindex orders the row indexes.

In [ ]:
df.reset_index(inplace=True, drop= True)
df.head(5)

mpg  cylinders  displacement  ...  origin                   name  mpg_zscore
0  17.0          6         163.0  ...       2            volvo 264gl   -0.834543
1  13.0          8         302.0  ...       1  ford gran torino (sw)   -1.346959
2  32.2          4         108.0  ...       3         toyota corolla    1.112638
3  18.1          6         258.0  ...       1        amc concord d/l   -0.693628
4  19.8          6         200.0  ...       1       mercury zephyr 6   -0.475852

[5 rows x 10 columns]

### Sorting

In [ ]:
df.sort_values(by= 'name', ascending=True)
print(f"The first car is : {df['name'].iloc[0]}")
pd.set_option('display.max_rows', 5)
display(df)

The first car is : volvo 264gl


mpg  cylinders  displacement  ...  origin                   name  mpg_zscore
0    17.0          6         163.0  ...       2            volvo 264gl   -0.834543
1    13.0          8         302.0  ...       1  ford gran torino (sw)   -1.346959
..    ...        ...           ...  ...     ...                    ...         ...
396  37.2          4          86.0  ...       3             datsun 310    1.753158
397  13.0          8         350.0  ...       1              chevy c10   -1.346959

[398 rows x 10 columns]

### Grouping Dataset

In [ ]:
g = df.groupby('cylinders')['mpg'].mean()
g

cylinders
3    20.550000
4    29.286765
5    27.366667
6    19.985714
8    14.963107
Name: mpg, dtype: float64

In [ ]:
# put it in a directory
d = g.to_dict()
d

{3: 20.55,
 4: 29.28676470588236,
 5: 27.366666666666664,
 6: 19.985714285714288,
 8: 14.963106796116508}

In [ ]:
# Storing count to dictionary
df.groupby('cylinders')['mpg'].count().to_dict()

{3: 4, 4: 204, 5: 3, 6: 84, 8: 103}

## 2.4 Using Apply and Map in Pandas

The map method in Pandas operates on a single column. You provide map with a dictionary of values to transform the target column.

In [ ]:
df['origin_name'] = df['origin'].map(
        {1: 'North America', 2: 'Europe', 3: 'Asia'}
)

# Display
pd.set_option('display.max_columns', 7)
pd.set_option('display.max_rows', 10)
display(df)

mpg  cylinders  displacement  ...                       name  \
0    17.0          6         163.0  ...                volvo 264gl   
1    13.0          8         302.0  ...      ford gran torino (sw)   
2    32.2          4         108.0  ...             toyota corolla   
3    18.1          6         258.0  ...            amc concord d/l   
4    19.8          6         200.0  ...           mercury zephyr 6   
..    ...        ...           ...  ...                        ...   
393  13.0          8         360.0  ...     plymouth custom suburb   
394  13.0          8         400.0  ...  chevrolet caprice classic   
395  20.3          5         131.0  ...                  audi 5000   
396  37.2          4          86.0  ...                 datsun 310   
397  13.0          8         350.0  ...                  chevy c10   

     mpg_zscore    origin_name  
0     -0.834543         Europe  
1     -1.346959  North America  
2      1.112638           Asia  
3     -0.693628  North America  
4     -0.475852  North America  
..          ...            ...  
393   -1.346959  North America  
394   -1.346959  North America  
395   -0.411800         Europe  
396    1.753158           Asia  
397   -1.346959  North America  

[398 rows x 11 columns]

### Using Apply with Dataframes

The apply function of the data frame can run a function over the entire data frame

In [ ]:
# The following code calculates a series called efficiency that is the displacement divided by horsepower.

efficiency = df.apply(lambda x: x['displacement'] / x['horsepower'], axis=1)
display(efficiency[0:10])

0    1.304000
1    2.157143
2    1.440000
3    2.150000
4    2.352941
5    1.410526
6    2.120000
7    1.363636
8    1.300000
9    1.272727
dtype: float64

In [ ]:
df['efficiency'] = efficiency

### Feature Engineering with Apply and Map

In this section, we will see how to calculate a complex feature using map, apply, and grouping. The data set is the following CSV

https://www.irs.gov/pub/irs-soi/16zpallagi.csv
This URL contains US Government public data for "SOI Tax Stats - Individual Income Tax Statistics." The entry point to the website is here:

https://www.irs.gov/statistics/soi-tax-stats-individual-income-tax-statistics-2016-zip-code-data-soi
Documentation describing this data is at the above link.

STATE - The state (e.g., MO)
zipcode - The zipcode (e.g. 63017)
agi_stub - Six different brackets of annual income (1 through 6)
N1 - The number of tax returns for each of the agi_stubs

In [ ]:
agi_file = 'https://www.irs.gov/pub/irs-soi/16zpallagi.csv'

In [ ]:
df_agi = pd.read_csv(agi_file)

In [ ]:
# Remove all records that have zip code 0 or 99999
df_agi = df_agi.loc[(df_agi['zipcode'] != 0) & (df_agi['zipcode'] != 99999),
           ['STATE', 'zipcode', 'agi_stub', 'N1']  ]

pd.set_option('display.max_columns', 0)
pd.set_option('display.max_rows', 7)

display(df_agi)

STATE  zipcode  agi_stub    N1
6         AL    35004         1  1510
7         AL    35004         2  1410
8         AL    35004         3   950
...      ...      ...       ...   ...
179787    WY    83414         4     0
179788    WY    83414         5    40
179789    WY    83414         6    30

[179184 rows x 4 columns]

In [ ]:
# Replace AGI with Median value

medians = {1:12500,2:37500,3:62500,4:87500,5:112500,6:212500}

df_agi['agi_stub'] = df_agi.agi_stub.map(medians)

pd.set_option('display.max_columns', 0)
pd.set_option('display.max_rows', 7)

display(df_agi)

STATE  zipcode  agi_stub    N1
6         AL    35004     12500  1510
7         AL    35004     37500  1410
8         AL    35004     62500   950
...      ...      ...       ...   ...
179787    WY    83414     87500     0
179788    WY    83414    112500    40
179789    WY    83414    212500    30

[179184 rows x 4 columns]

In [ ]:
# group by zip code
groups = df_agi.groupby('zipcode')

In [ ]:
groups

In [ ]:
# Calculate AGI estimate - Apply lambda across groups

df_agi = pd.DataFrame(groups.apply(
    lambda x: sum(x['N1'] * x['agi_stub']) / sum(x['N1']))).reset_index()

In [ ]:
df_agi.columns = ['zipcode','agi_estimate']

In [ ]:
pd.set_option('display.max_columns', 0)
pd.set_option('display.max_rows', 10)

display(df_agi)

zipcode  agi_estimate
0         1001  52895.322940
1         1002  64528.451001
2         1003  15441.176471
3         1005  54694.092827
4         1007  63654.353562
...        ...           ...
29867    99921  48042.168675
29868    99922  32954.545455
29869    99925  45639.534884
29870    99926  41136.363636
29871    99929  45911.214953

[29872 rows x 2 columns]

# Part 2.5: Feature Engineering

You can obtain your own key from this link: Google API Keys.

https://developers.google.com/maps/documentation/embed/get-api-key


# Tensorflow Keras


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import numpy as np

In [ ]:
# create XOR dataset
x = np.array([
            [0, 0],
            [1, 0],
            [0, 1],
            [1, 1]
            ])

y = np.array([
              0,
              1,
              1,
              0
            ])

In [ ]:
# Build the network
#SGD = optimizer.SGD(Lr = 0.01, decay = le-6, momentum =0.9, nestrov = True)

done = False
cycle = 1

while not done:
    print("Cycle#{}".format(cycle))
    cycle+=1
    model = Sequential()
    model.add(Dense(2, input_dim = 2, activation='relu'))
    model.add(Dense(1))
    model.compile(loss = 'mean_squared_error', optimizer= 'adam')
    model.fit(x, y, verbose = 0, epochs = 10000)

    # Predict
    pred = model.predict(x)

    # check if successful?  It takes several runs with this small of a network
    done = pred[0]<0.01 and pred[3]<0.01 and pred[1] > 0.9 and pred[2] > 0.9
    print(pred)


Cycle#1
[[0.49999997]
 [0.49999997]
 [0.49999997]
 [0.49999997]]
Cycle#2
[[0.49999994]
 [0.49999997]
 [0.5       ]
 [0.5       ]]
Cycle#3
[[6.6666657e-01]
 [6.6666657e-01]
 [6.6666657e-01]
 [5.9604645e-08]]
Cycle#4
[[ 6.2698092e-08]
 [ 1.0000000e+00]
 [ 9.9999994e-01]
 [-2.1949424e-08]]


In [ ]:
pred

array([[ 6.2698092e-08],
       [ 1.0000000e+00],
       [ 9.9999994e-01],
       [-2.1949424e-08]], dtype=float32)